# Generated by Django 4.0.6 on 2022-11-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mname', models.CharField(max_length=30)),
                ('Dname', models.CharField(max_length=30)),
                ('Hero', models.CharField(max_length=30)),
                ('Heroine', models.CharField(max_length=30)),
                ('Rdate', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
